/* The looks Kawach can wear: a style (how screens are built) and a colouring
 * (the colours they are painted in), chosen in Settings > How it looks.
 *
 * Charts is the default style, and every new feature is built in it first
 * (decided 2 Oct 2026); Tactile, Peaks and Mindora follow in later releases.
 * A colouring is a set of token values in css/looks.css (generated by
 * tools/looks.py), switched on by data-colour on <html>. Each colouring is
 * light or dark by nature, and data-theme follows it, so the light and dark
 * material already in the stylesheets (glass, sheen, shadow) comes with it.
 *
 * index.html applies the same choice inline before the first paint; the ids
 * of light colourings are listed there too and must match LIGHT here.
 */

export const STYLES = [
  { id: 'charts', name: 'Charts', ready: true, note: 'Gradient rings, waves and columns.' },
  { id: 'tactile', name: 'Tactile', ready: true, note: 'Raised cards, pressed-in fields, metal switches.' },
  { id: 'peaks', name: 'Peaks', ready: true, note: 'A pale panel up top, the month as mountains.' },
  { id: 'mindora', name: 'Mindora', ready: false },
];

// Ground, accent, second accent, money in: the four dots a swatch shows.
export const COLOURINGS = [
  { id: 'charts', name: 'Charts', mode: 'dark', bg: '#050505', dots: ['#171717', '#f47ebc', '#7c62f2', '#7efdb4'] },
  { id: 'tactile', name: 'Tactile copper', mode: 'dark', bg: '#222125', dots: ['#38373c', '#b0552f', '#e2906a', '#d9d2cb'] },
  { id: 'peaks', name: 'Peaks slate', mode: 'dark', bg: '#1c2328', dots: ['#eef6f6', '#fd8242', '#f6b74c', '#1efae0'] },
  { id: 'ember-dusk', name: 'Ember dusk', mode: 'dark', bg: '#101c30', dots: ['#143041', '#e2773a', '#ffcb68', '#5fb3a8'] },
  { id: 'strawberry-night', name: 'Strawberry night', mode: 'dark', bg: '#142030', dots: ['#1e3442', '#ff5c8d', '#a83a78', '#85a3b2'] },
  { id: 'flame-light', name: 'Burning flame, light', mode: 'light', bg: '#eee9df', dots: ['#f8f5ef', '#a35139', '#ffb162', '#2c3b4d'] },
  { id: 'flame-dark', name: 'Burning flame, dark', mode: 'dark', bg: '#1b2632', dots: ['#2c3b4d', '#ffb162', '#a35139', '#c9c1b1'] },
  { id: 'feather-forest', name: 'Feather forest', mode: 'dark', bg: '#071f1b', dots: ['#0b2e29', '#d77428', '#3f8f83', '#b53f0d'] },
  { id: 'atelier', name: 'Atelier', mode: 'dark', bg: '#222326', dots: ['#2e3033', '#c25a36', '#ccac8a', '#8a8350'] },
];

// "Follow my phone": the style's own colours when the phone is dark (each
// style brings a colouring of its own), burning flame light when it is light.
export const AUTO = { dark: 'charts', light: 'flame-light' };
const OWN = { charts: 'charts', tactile: 'tactile', peaks: 'peaks' };

/* The colouring a style wears by its own choice: 'Follow my phone' when dark. */
export const ownColouring = (style) => OWN[style] || AUTO.dark;

const byId = new Map(COLOURINGS.map((c) => [c.id, c]));

/* The colouring actually worn for a choice ('auto' or an id). */
export function colouringFor(choice, prefersLight, style = 'charts') {
  if (byId.has(choice)) return byId.get(choice);
  return byId.get(prefersLight ? AUTO.light : OWN[style] || AUTO.dark);
}

/* The style worn: one that is ready, or Charts. */
export function styleFor(choice) {
  return STYLES.some((s) => s.id === choice && s.ready) ? choice : 'charts';
}

function prefersLight() {
  return Boolean(window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches);
}

/* Puts a choice on <html>: the colouring, its light or dark, and the colour
 * the phone draws its own bar in. */
export function applyColouring(choice, styleChoice = 'charts') {
  const style = styleFor(styleChoice);
  const c = colouringFor(choice, prefersLight(), style);
  const root = document.documentElement;
  if (style === 'charts') root.removeAttribute('data-style');
  else root.setAttribute('data-style', style);
  root.setAttribute('data-colour', c.id);
  root.setAttribute('data-theme', c.mode);
  for (const meta of document.querySelectorAll('meta[name="theme-color"]')) meta.setAttribute('content', c.bg);
  return c;
}
