/* The Kawach visual catalogue.
 *
 * One record per approved visual component, so a future instruction can say
 * "use KAWACH-CHART-CASH-RIVER-V1 on History" and mean exactly one thing.
 *
 * This file is the register, not the implementation. Every component here is
 * drawn by code that already ships in the app - js/charts.js, css/dna.css,
 * js/brand.js - and the Lab renders each entry by calling that same code. A
 * catalogue of pictures would go stale the first time a component changed;
 * this one cannot, because it is the component.
 *
 * Loaded only by /lab/. The app never imports it and the service worker does
 * not cache it: deleting this folder leaves Kawach exactly as it is.
 *
 * STATUS
 *   LIVE        in production today, on the screens named
 *   TESTING     built and covered by tests, not yet placed on a screen
 *   PROPOSED    sketched here for discussion, not built
 *   DEPRECATED  superseded; kept so an older reference still resolves
 *
 * A component is never edited in place once it is LIVE. It gets a new
 * version - V2 - and V1 stays where it is.
 */

export const STATUS = ['LIVE', 'TESTING', 'PROPOSED', 'DEPRECATED'];

export const CATALOGUE = [
  /* ---------------------------------------------------------------- HERO */
  {
    id: 'KAWACH-HERO-MONEY-V1',
    section: 'hero',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'One figure that is the answer to the screen.',
    answers: 'What is the single number I came here for?',
    screens: ['Summary', 'History', 'Accounts', 'Plan', 'Coach'],
    deps: ['css/dna.css .k-hero', 'js/ui.js hero()'],
    contract: '{ label, amount, negative }',
    variants: ['positive', 'negative'],
    notes: 'One per screen. A second hero means two answers and no hierarchy.',
    dont: 'Never put a hero inside a card that already has a figure.',
  },
  {
    id: 'KAWACH-HERO-METRICS-V1',
    section: 'hero',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'The hero figure with the two or three figures that explain it.',
    answers: 'What is the number, and what is it made of?',
    screens: ['Summary'],
    deps: ['css/dna.css .k-hero', '.hero-under', '.stat-k/.stat-v'],
    contract: '{ label, amount, figures: [{label, value}] }',
    variants: ['positive', 'neutral', 'warning'],
    notes: 'Label above value, never beside it.',
    dont: 'Do not repeat a figure that the breakdown below already lists.',
  },
  {
    id: 'KAWACH-HERO-LEFT-TO-SPEND-V1',
    section: 'hero',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'The full Summary composition: period, figure, meter, verdict.',
    answers: 'How much can I safely spend, until when, and is anything wrong?',
    screens: ['Summary'],
    deps: ['KAWACH-HERO-METRICS-V1', 'free-to-spend.js level + bankShortfall'],
    contract: '{ free, limit, cycleStart, cycleKey, level, bankShortfall }',
    variants: ['ok', 'warning', 'critical', 'over'],
    notes: 'The verdict line is never calmer than the bank check beneath it.',
    dont: 'Do not show a daily allowance while bankShortfall is above zero.',
  },

  /* --------------------------------------------------------------- CHART */
  {
    id: 'KAWACH-CHART-BUDGET-BURN-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'Cumulative spending against an even pace.',
    answers: 'Am I ahead or behind for this point in the period?',
    screens: ['Summary'],
    deps: ['js/charts.js burnLine()'],
    contract: '{ totals[], budget, days, shortfall }',
    notes: 'Says the shortfall in its own note so it cannot contradict the hero.',
    dont: 'Do not draw before three days of a period have passed.',
  },
  {
    id: 'KAWACH-CHART-COMMITMENT-METER-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'A ring showing the share of the month already promised.',
    answers: 'Before I decide anything, how much is already committed?',
    screens: ['Summary', 'Plan'],
    deps: ['js/charts.js radialMeter()'],
    contract: '{ committed, income }',
    variants: ['under', 'over'],
    notes: 'Guards zero income, nothing committed, and more committed than there is.',
    dont: 'Never feed it a budget as income - committed + budget must equal income.',
  },
  {
    id: 'KAWACH-CHART-SPENDING-PULSE-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'One bar a day across the period, biggest day lit.',
    answers: 'When in the period does my spending actually happen?',
    screens: ['Summary'],
    deps: ['js/charts.js spendingPulse()', 'free-to-spend.js spendByDay'],
    contract: '{ days: [{date, amount}], today }',
    notes: 'A quiet day keeps a stub so it reads as nearly nothing, not missing.',
    dont: 'Do not compute the daily series here - take spendByDay from the model.',
  },
  {
    id: 'KAWACH-CHART-ALLOCATION-RING-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'How one total splits, with every figure listed beside it.',
    answers: 'How is what I hold divided?',
    screens: ['Accounts', 'Summary'],
    deps: ['js/charts.js allocationRing()'],
    contract: '{ slices: [{label, amount}], centre, caption }',
    variants: ['standard', 'compact', 'hero'],
    notes: 'The legend is the part that must reconcile with the total above it.',
    dont: 'Never draw it with fewer than two positive slices; it returns nothing.',
  },
  {
    id: 'KAWACH-CHART-CASH-RIVER-V1',
    section: 'chart',
    status: 'TESTING',
    since: '2026-09-26',
    purpose: 'Money in and out as two lines, the gap between them shaded.',
    answers: 'Is more coming in than going out, and how has that changed?',
    screens: [],
    deps: ['js/charts.js cashRiver()'],
    contract: '{ months: [{label, in, out}] }',
    notes: 'Built and tested. Not placed: History already answers this with IN-OUT-V1.',
    dont: 'Do not shade to a baseline the axis does not start at.',
  },
  {
    id: 'KAWACH-CHART-IN-OUT-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'Six months of money in against money out, as paired bars.',
    answers: 'Is this month normal for me?',
    screens: ['History'],
    deps: ['js/charts.js inOutBars()'],
    contract: '{ months: [{label, in, out}] }',
    notes: 'The one drawing with a legend, because two things are compared.',
    dont: 'Do not use alongside CASH-RIVER-V1 on one screen.',
  },
  {
    id: 'KAWACH-CHART-CATEGORY-RANKING-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'Where the money went, biggest first, as ranked bars.',
    answers: 'What did I actually spend on?',
    screens: ['Recap'],
    deps: ['js/charts.js categoryBars()'],
    contract: '{ items: [{name, amount}], top }',
    notes: 'Replaced a bubble chart: a ranked bar stays readable at 320px.',
    dont: 'Never a pie for this - slices cannot be compared by eye.',
  },
  {
    id: 'KAWACH-CHART-COMMITTED-BAR-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'One bar in three parts: must go out, can flex, free.',
    answers: 'How is this month divided before I spend anything?',
    screens: ['Plan'],
    deps: ['js/charts.js committedBar()'],
    contract: '{ must, flex, free, legend }',
    notes: 'Legend off when the screen already lists the same three figures.',
    dont: 'Do not print the same number as a bar and as a row.',
  },
  {
    id: 'KAWACH-CHART-GOAL-RING-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'Progress toward one savings goal.',
    answers: 'How close am I, and what does a month get me?',
    screens: ['Plan'],
    deps: ['js/charts.js goalRing()', 'js/goals.js goalProgress()'],
    contract: '{ saved, target, monthly, by }',
    dont: 'Not a general progress ring - use COMMITMENT-METER-V1 for shares.',
  },
  {
    id: 'KAWACH-CHART-RUNWAY-V1',
    section: 'chart',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'How many months the money would last with nothing coming in.',
    answers: 'If income stopped, how long do I have?',
    screens: ['Summary (business)'],
    deps: ['js/charts.js runwayBar()', 'js/business.js businessRunway()'],
    contract: '{ covered, needPerMonth, have, max }',
    notes: 'For uneven income. A salary has a payday, so it has no runway.',
    dont: 'Do not show for a salaried profile.',
  },

  /* ------------------------------------------------------------- INSIGHT */
  {
    id: 'KAWACH-INSIGHT-CALM-V1',
    section: 'insight',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'Nothing needs attention, said once.',
    answers: 'Am I fine?',
    screens: ['Summary'],
    deps: ['css/dna.css .k-context--calm'],
    contract: '{ title, body }',
    notes: 'Tone is decided by the caller from real state, never by the component.',
    dont: 'Never manufacture a reassurance the data does not support.',
  },
  {
    id: 'KAWACH-INSIGHT-ATTENTION-V1',
    section: 'insight',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'A period running out, or a limit getting close.',
    answers: 'Is something about to matter?',
    screens: ['Summary', 'Coach'],
    deps: ['css/dna.css .k-context--attention'],
    contract: '{ title, body }',
    dont: 'Do not use for money already gone - that is ALERT.',
  },
  {
    id: 'KAWACH-INSIGHT-ALERT-V1',
    section: 'insight',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'Money owed, or spending outside its usual range.',
    answers: 'What is actually wrong?',
    screens: ['Summary', 'Coach'],
    deps: ['css/dna.css .k-context--alert'],
    contract: '{ title, body }',
    notes: 'Says why, with the figure, not just a red border.',
    dont: 'Never colour-code without naming the cause.',
  },

  /* ------------------------------------------------------------- ACCOUNT */
  {
    id: 'KAWACH-ACCOUNT-BALANCE-V1',
    section: 'account',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'One account as one row: mark, name, context, balance.',
    answers: 'What is in this account?',
    screens: ['Accounts'],
    deps: ['css/dna.css .account-row', 'js/brand.js brandMark()'],
    contract: '{ account, meta, value, tone }',
    notes: 'The balance is the largest thing in the row and never wraps.',
    dont: 'Do not give each account its own card - a list is one surface.',
  },
  {
    id: 'KAWACH-ACCOUNT-ALLOCATION-V1',
    section: 'account',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'ALLOCATION-RING-V1 applied to the accounts you can spend from.',
    answers: 'Where is my money sitting?',
    screens: ['Accounts'],
    deps: ['KAWACH-CHART-ALLOCATION-RING-V1'],
    contract: '{ slices from spendable accounts with a known balance }',
    notes: 'Money put away is excluded, or the same money is shown twice.',
    dont: 'Never include savings or PF in the ring beside the spendable total.',
  },

  /* --------------------------------------------------------------- ROW */
  {
    id: 'KAWACH-ROW-TRANSACTION-V1',
    section: 'row',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'One payment as one line, with the rest behind a tap.',
    answers: 'What was this payment?',
    screens: ['History', 'Accounts', 'Coach'],
    deps: ['css/dna.css .k-row', '.hist-row'],
    contract: '{ title, meta, value, tone }',
    dont: 'Do not repeat a warning per row - say it once above the list.',
  },
  {
    id: 'KAWACH-ROW-TRANSACTION-BRAND-V1',
    section: 'row',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'A transaction row carrying the merchant mark.',
    answers: 'Who was this paid to?',
    screens: ['History', 'Accounts'],
    deps: ['KAWACH-ROW-TRANSACTION-V1', 'js/brand.js brandMark()'],
    contract: '{ name, category, size }',
    notes: 'Resolver order: licensed SVG, category icon, monogram.',
    dont: 'Never draw an approximation of a trademark.',
  },

  /* ------------------------------------------------------------ PLANNING */
  {
    id: 'KAWACH-PLAN-COMMITMENT-V1',
    section: 'planning',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'A monthly commitment as a row you tap to edit.',
    answers: 'What goes out every month, and when?',
    screens: ['Plan'],
    deps: ['css/dna.css .plan-row', '.plan-row-wrap'],
    contract: '{ label, monthly, when, account }',
    notes: 'Removing keeps its own button - never a thing you do by tapping a row.',
    dont: 'Do not reorder the list automatically; the order is the owner’s.',
  },
  {
    id: 'KAWACH-PLAN-GOAL-V1',
    section: 'planning',
    status: 'LIVE',
    since: '2026-09-26',
    purpose: 'A savings goal: ring, name, what a month gets you there.',
    answers: 'Will I make it, and what does it take?',
    screens: ['Plan'],
    deps: ['KAWACH-CHART-GOAL-RING-V1'],
    contract: '{ name, target, saved, by, monthly }',
    dont: 'Do not show a goal without the monthly figure - a target alone is a wish.',
  },

  /* --------------------------------------------------------------- STATE */
  {
    id: 'KAWACH-STATE-EMPTY-V1',
    section: 'state',
    status: 'LIVE',
    since: '2026-09-25',
    purpose: 'Nothing here yet, and the one way to change that.',
    answers: 'Why is this screen blank?',
    screens: ['Accounts', 'Plan', 'History', 'Coach'],
    deps: ['css/dna.css .k-empty', 'js/ui.js emptyState()'],
    contract: '{ what, why, action }',
    notes: 'One action. Two buttons a finger apart read as two different things.',
    dont: 'Do not repeat the action if the screen already offers it nearby.',
  },
  {
    id: 'KAWACH-STATE-SUCCESS-V1',
    section: 'state',
    status: 'TESTING',
    since: '2026-09-25',
    purpose: 'Something worked, said briefly.',
    answers: 'Did that save?',
    screens: [],
    deps: ['css/dna.css .k-state'],
    contract: '{ title, body }',
    notes: 'Production currently uses the toast. This is the in-page form.',
    dont: 'Do not use for anything the user must act on.',
  },
  {
    id: 'KAWACH-STATE-ERROR-V1',
    section: 'state',
    status: 'TESTING',
    since: '2026-09-25',
    purpose: 'Something failed, and what survived.',
    answers: 'What broke, and did I lose anything?',
    screens: [],
    deps: ['css/dna.css .k-state--error'],
    contract: '{ title, body }',
    notes: 'Says what survived before it says what broke.',
    dont: 'Never blame the person.',
  },
  {
    id: 'KAWACH-STATE-LOADING-V1',
    section: 'state',
    status: 'TESTING',
    since: '2026-09-25',
    purpose: 'The shape of what is coming, while it comes.',
    answers: 'Is it working?',
    screens: [],
    deps: ['css/dna.css .k-skeleton'],
    contract: 'none - sized by the caller',
    notes: 'Screens render after their awaits, so this is rarely needed.',
    dont: 'Do not show for anything that resolves in under a frame.',
  },
];

/* Kawach's own artwork. Original, offline, no third-party mark anywhere. */
export const ARTWORK = [
  { file: 'empty-wallet.svg', use: 'KAWACH-STATE-EMPTY-V1 on Accounts', status: 'TESTING' },
  { file: 'all-clear.svg', use: 'KAWACH-STATE-SUCCESS-V1', status: 'TESTING' },
  { file: 'something-broke.svg', use: 'KAWACH-STATE-ERROR-V1', status: 'TESTING' },
  { file: 'shield-motif.svg', use: 'Quiet accent; the name means shield', status: 'TESTING' },
];

export const bySection = (name) => CATALOGUE.filter((c) => c.section === name);
export const byStatus = (name) => CATALOGUE.filter((c) => c.status === name);
export const find = (id) => CATALOGUE.find((c) => c.id === id) || null;
